### ISSUE TITLE
Add deprecated ModelicaLicense2

### ISSUE THREAD

**Issue by GallLeo** [modelica/www.modelica.org#65] opened 2024-02-05 08:33 UTC
Many people still link to 
http://www.modelica.org/licenses/ModelicaLicense2

So, I think we should re-upload the old license.
With a note, that it should not be used for new libraries.
Alternatives are BSB 3-clause (like MSL) or the extended version of BSD (like Buildings, which simplifies accepting pull requests).

**Comment by beutlich** [comment] 2024-03-03 16:37
Is this a duplicate of #45?

**Comment by t-sommer** [comment] 2024-05-27 19:24
Fixed with #84.

**Closed by t-sommer** 2024-05-27 19:24 UTC
